services:
  mpl.logging.milestone.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Storage=AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://my-azurite:10000/devstoreaccount1;QueueEndpoint=http://my-azurite:10001/devstoreaccount1;TableEndpoint=http://my-azurite:10002/devstoreaccount1;

    ports:
      - "8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro

  mpl.logging.milestone.worker:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__Storage=AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://my-azurite:10000/devstoreaccount1;QueueEndpoint=http://my-azurite:10001/devstoreaccount1;TableEndpoint=http://my-azurite:10002/devstoreaccount1;
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro

  my-azurite:
    command:
      - "azurite"
      - "--queueHost"
      - "0.0.0.0"
      - "--blobHost"
      - "0.0.0.0"
      - "--tableHost"
      - "0.0.0.0"
      - "--disableProductStyleUrl"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite:/opt/azurite/


volumes:
  azurite: {}